spring.application.name=intelligent-analysis-platform
connector.pool.max-pool-size=5
connector.pool.connection-timeout-ms=3000
connector.pool.idle-timeout-ms=600000
connector.query.default-timeout-ms=10000
connector.query.default-page-size=200
connector.query.default-cache-ttl-seconds=60
analysis.execution.async.core-pool-size=4
analysis.execution.async.max-pool-size=8
analysis.execution.async.queue-capacity=100
analysis.governance.slow-query-threshold-ms=5000
analysis.governance.tenant-qps-limit=20
analysis.governance.datasource-concurrency-limit=10
management.endpoints.web.exposure.include=health,info
spring.datasource.url=public-xm-d5-cds-staging-node9.idchb1az1.hb1.kwaidc.com:15612
spring.datasource.username=gifshow_15612_v1_ro
spring.datasource.password=Kv1heRZTAqmI1Mxy7uFov4rC2O6GHc5J
spring.sql.init.mode=always
