package com.kuaishou.intelligentanalysisplatform.common.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_ARGUMENT("INVALID_ARGUMENT", HttpStatus.BAD_REQUEST),
    VALIDATION_FAILED("VALIDATION_FAILED", HttpStatus.BAD_REQUEST),
    QUERY_VALIDATION_FAILED("QUERY_VALIDATION_FAILED", HttpStatus.UNPROCESSABLE_ENTITY),
    UNSUPPORTED_NODE_TYPE("UNSUPPORTED_NODE_TYPE", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED("UNAUTHORIZED", HttpStatus.UNAUTHORIZED),
    DATASOURCE_ACCESS_DENIED("DATASOURCE_ACCESS_DENIED", HttpStatus.FORBIDDEN),
    DATASOURCE_NOT_FOUND("DATASOURCE_NOT_FOUND", HttpStatus.NOT_FOUND),
    DATASOURCE_ALREADY_EXISTS("DATASOURCE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    DATASOURCE_CONNECTION_FAILED("DATASOURCE_CONNECTION_FAILED", HttpStatus.BAD_GATEWAY),
    DATASOURCE_INVALID_CREDENTIAL("DATASOURCE_INVALID_CREDENTIAL", HttpStatus.UNPROCESSABLE_ENTITY),
    DATASOURCE_ENCRYPTION_ERROR("DATASOURCE_ENCRYPTION_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    WORKFLOW_NOT_FOUND("WORKFLOW_NOT_FOUND", HttpStatus.NOT_FOUND),
    NODE_NOT_FOUND("NODE_NOT_FOUND", HttpStatus.NOT_FOUND),
    SQL_SECURITY_REJECTED("SQL_SECURITY_REJECTED", HttpStatus.UNPROCESSABLE_ENTITY),
    SQL_MULTI_STATEMENT_REJECTED("SQL_MULTI_STATEMENT_REJECTED", HttpStatus.BAD_REQUEST),
    SQL_NOT_READONLY("SQL_NOT_READONLY", HttpStatus.BAD_REQUEST),
    SQL_LOCK_CLAUSE_FORBIDDEN("SQL_LOCK_CLAUSE_FORBIDDEN", HttpStatus.BAD_REQUEST),
    SQL_FORBIDDEN_STATEMENT("SQL_FORBIDDEN_STATEMENT", HttpStatus.BAD_REQUEST),
    SQL_PARSE_FAILED("SQL_PARSE_FAILED", HttpStatus.BAD_REQUEST),
    QUERY_LIMIT_EXCEEDED("QUERY_LIMIT_EXCEEDED", HttpStatus.BAD_REQUEST),
    REQUEST_CONFLICT("REQUEST_CONFLICT", HttpStatus.CONFLICT),
    RATE_LIMITED("RATE_LIMITED", HttpStatus.TOO_MANY_REQUESTS),
    QUERY_TIMEOUT("QUERY_TIMEOUT", HttpStatus.GATEWAY_TIMEOUT),
    QUERY_CANCELLED("QUERY_CANCELLED", HttpStatus.BAD_REQUEST),
    QUERY_ALREADY_CANCELLED("QUERY_ALREADY_CANCELLED", HttpStatus.CONFLICT),
    QUERY_RESULT_TRUNCATED("QUERY_RESULT_TRUNCATED", HttpStatus.OK),
    NODE_EXECUTION_FAILED("NODE_EXECUTION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    EXECUTION_RECORD_NOT_FOUND("EXECUTION_RECORD_NOT_FOUND", HttpStatus.NOT_FOUND),
    ASYNC_TASK_NOT_FOUND("ASYNC_TASK_NOT_FOUND", HttpStatus.NOT_FOUND),
    ASYNC_TASK_RUNNING("ASYNC_TASK_RUNNING", HttpStatus.ACCEPTED),
    ASYNC_TASK_FAILED("ASYNC_TASK_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DOWNSTREAM_ERROR("DOWNSTREAM_ERROR", HttpStatus.BAD_GATEWAY),
    INTERNAL_ERROR("INTERNAL_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    NOT_IMPLEMENTED("NOT_IMPLEMENTED", HttpStatus.NOT_IMPLEMENTED);

    private final String code;
    private final HttpStatus httpStatus;

    ErrorCode(String code, HttpStatus httpStatus) {
        this.code = code;
        this.httpStatus = httpStatus;
    }

    public String getCode() {
        return code;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }
}
